### ISSUE TITLE
Cannot set up an environment with Drupal 8.4.x or higher

### ISSUE THREAD

**Issue by aiwata55** [awslabs/eb-php-drupal#2]
I tried installation of Drupal 8.x several times in the last few days.  At first, I chose Tokyo region but couldn't upload the source code.  I guessed it was because the script cannot set up a S3 bucket in Tokyo.

So I change my region to Oregon.  This time EB accepted the source code of Drupal 8.5.0.  But accessing the URL of the site doesn't show anything.  It's a "the server isn't responding" error (maybe 404?).

Can you figure out if anything in this script must be updated?  Please take a look at it.  Thank you in advance.

**Comment by mwunderl** [comment]
The configuration file format changed since 8.3. I've updated the sample config.
Thanks,
-Michael
